### ISSUE TITLE
Drive - Diff Drive

### ISSUE THREAD

**Issue by Bread-n-Butter06** [team401/2024-everybot#1]
Create and implement drive subsystem (swerve? tank?)

**Comment by linglejack06** [comment]
@jkleiber could you look at the Diff-Drive branch, GitHub is showing that it is behind main but I have merged main branch into diff-drive and the commits from main are showing up on the remote Diff-Drive branch? (meaning it should not be behind)

**Comment by jkleiber** [comment]
@linglejack06 If you look at the github network [here](https://github.com/team401/2024-everybot/network), the Diff-Drive branch is based way back in the repo with many merges to keep it updated.

Since the branch has been updated with merge rather than rebase, it's relatively painful to understand the history. It would be easier to figure out if the branch is mergeable if you open a PR for it and see if there are any merge conflicts with main.

Also, since you've done merge to update this branch, it could be difficult to recover linear history with rebase. So I wouldn't do that, and just keep updating this particular branch with merge

**Comment by linglejack06** [comment]
@jkleiber will the navigation system work how it is now? Ie will it get the latest inputs in its own periodic or will it be out of date by one 20ms cycle?

**Comment by jkleiber** [comment]
@linglejack06 I think the data should stay current if the suppliers always ask for the latest information from IO
